name: Build Binaries

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  build-binaries:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Pack npm package
        run: npm pack
        id: pack
      
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-binary
          path: '**/*.node'