name: Build Binaries

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  build-binaries:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, ia32]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run build -- --arch ${{ matrix.arch }}

      - name: Run tests
        run: npm test
      
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-binary-${{ matrix.arch }}
          path: '**/*.node'