name: Build Binaries

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  build-binaries:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, ia32, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: matrix.arch == 'ia32'
        uses: actions/setup-node@v4
        with:
          architecture: 'x86'
          node-version: '18'

      - name: Setup Node.js
        if: matrix.arch != 'ia32'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --arch ${{ matrix.arch }}

      - name: Test
        run: npm test
      
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-binary-${{ matrix.arch }}
          path: '**/*.node'