name: Release 

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-binaries.yml

  release:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: node-binary-x64
          path: ./build/Release

      - name: Publish package to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}