name: Release 

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-binaries.yml

  release:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: node-binary
          path: ./build/Release

      - name: Test
        run: npm test

      - name: Publish package to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}