name: Release 

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    environment: production
    runs-on: windows-latest
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: npm-package
          path: ./artifact-directory

      - name: List files in the artifact directory
        run: dir artifact-directory
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Publish package to npm
        run: npm publish artifact-directory/*.tgz --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}