name: Release 

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: node-binary
          path: ./build/Release

      - name: Run tests
        run: npm test
      
      - name: List all files recursively
        run: ls -R